version: "3.9"
services:
    backend:
        build: .
        restart: on-failure:3
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            SQLALCHEMY_DATABASE_URL: postgresql+asyncpg://db:password@db/mydb
            JWT_SECRET_KEY: "f7bfef017ef0b30c0fa8de9caff04253939b6916b15e47aa2d865db53266eb9a"
            JWT_ALGORITHM: "HS256"
            JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
            JWT_REFRESH_TOKEN_EXPIRE_DAYS: 1
            TOKEN_CLEANUP_MINUTES: 60

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
        ports:
            - "5432:5432"